# ==========================================================================
# WineMetalScan -- metal concentration estimation in wine by FT-MIR
# spectroscopy and machine learning. App for Posit Connect Cloud.
#
# Structure:
#   - One tab per analyte (potassium, magnesium, calcium, iron, copper).
#   - Each tab: scope / instrument / EDTA protocol information, model
#     validation status (metrics + plots of the winning model), and a
#     panel to upload a spectrum and get a prediction.
#   - Models are loaded at runtime from Models/*.rds (generated by
#     Build_Deployment_Models.R). If an .rds is not yet available, the
#     tab reports that instead of crashing.
# ==========================================================================

library(shiny)
library(bslib)
library(DT)
library(ggplot2)
library(openxlsx)

source("R/predict_utils.R")

# allow larger uploads than Shiny's 5 MB default (files with many spectra)
options(shiny.maxRequestSize = 30 * 1024^2)

MODELS_DIR <- "Models"
DATA_DIR   <- "data"

# --------------------------------------------------------------------
# Information common to the five analytes (instrument, reference
# method, Na2EDTA sample-preparation protocol, varietal/geographic
# scope).
# --------------------------------------------------------------------
COMMON_INFO <- list(
  instrument = paste(
    "Spectra acquired in duplicate with a MultiSpec system (TDI, Barcelona,",
    "Spain), equipped with a CETIM flow-through transmission cell (TDI,",
    "Barcelona, Spain) and a 40-position autosampler. Spectral range:",
    "902.57-3000.84 cm-1 (545 variables, ~3.86 cm-1 step)."),
  reference_method = paste(
    "Reference concentrations were determined by inductively coupled plasma",
    "optical emission spectrometry (ICP-OES), Spectrogreen FMD46 instrument",
    "(SPECTRO Analytical Instruments)."),
  edta_protocol = paste(
    "Sample preparation: add 2 mL of a 5% w/v aqueous Na2EDTA solution to 8 mL",
    "of wine (final volume 10 mL). Mix gently and let stand for 30 minutes at",
    "room temperature before measuring. The addition of Na2EDTA is necessary",
    "because metals do not absorb directly in the infrared; the formation of",
    "the metal-EDTA complex is what produces the spectral signal used by the",
    "model."),
  wine_scope = paste(
    "Spanish white and red wines from 20 Designations of Origin (Cadiz, Borja,",
    "Carinena, Castilla, Catalunya, Extremadura, Jumilla, La Jaraba, La Mancha,",
    "Madrid, Navarra, Penedes, Ribeiro, Ribera del Duero, Rioja, Rueda,",
    "Somontano, Toro, Ucles and Valdepenas) and 9 grape varieties (Airen,",
    "Garnacha, Merlot, Monastrell, Palomino, Sauvignon Blanc, Tempranillo,",
    "Verdejo and Viura)."),
  disclaimer = paste(
    "The values returned by this tool are ESTIMATES obtained with machine",
    "learning algorithms from the FT-MIR spectrum, and should be treated as",
    "INDICATIVE or screening values. They do not replace analysis by",
    "reference methods (ICP-OES/ICP-MS or other official OIV methods) and",
    "must not be used as the sole basis for enological, regulatory or",
    "commercial decisions.")
)

IVAGRO_URL <- "https://ivagro.uca.es"
APP_CODE_URL   <- "https://github.com/pablofacu86/WineMetalScan"
STUDY_CODE_URL <- "https://github.com/pablofacu86/Wine-Metals-FTMIR-ML"

# --------------------------------------------------------------------
# Analyte-specific configuration: scope, winning model, validation
# metrics and paths to the associated files. The numeric values are
# the ones reported in the study; the live validation/prediction
# panels are populated from the corresponding .rds bundle as soon as
# it is available (see load_bundle() below).
# --------------------------------------------------------------------
ANALYTES <- list(
  POTASSIUM = list(
    label = "Potassium", symbol = "K", unit = "mg/L", task = "regression",
    color = "#7B1E3A",
    scope_range = "290 - 1379 mg/L", n_samples = "100 (46 white, 54 red)",
    model_desc = "Elastic Net, no derivative or scatter correction, no variable selection (310 variables).",
    spiked = FALSE,
    model_file = file.path(MODELS_DIR, "POTASSIUM_model.rds"),
    sample_file = file.path(DATA_DIR, "Test_Set_App.xlsx"), sample_sheet = "POTASSIUM"
  ),
  MAGNESIUM = list(
    label = "Magnesium", symbol = "Mg", unit = "mg/L", task = "regression",
    color = "#3A5A40",
    scope_range = "47.9 - 118 mg/L", n_samples = "100 (46 white, 54 red)",
    model_desc = "PLS (5 latent variables), 1st derivative + MSC, Boruta selection (45 variables).",
    spiked = FALSE,
    model_file = file.path(MODELS_DIR, "MAGNESIUM_model.rds"),
    sample_file = file.path(DATA_DIR, "Test_Set_App.xlsx"), sample_sheet = "MAGNESIUM"
  ),
  CALCIUM = list(
    label = "Calcium", symbol = "Ca", unit = "mg/L", task = "regression",
    color = "#1D3557",
    scope_range = "45.0 - 295 mg/L (range extended by spiking, see note below)",
    n_samples = "160 (79 white, 81 red; includes spiked samples)",
    model_desc = "XGBoost, 1st derivative + SNV, Boruta selection (47 variables).",
    spiked = TRUE,
    model_file = file.path(MODELS_DIR, "CALCIUM_model.rds"),
    sample_file = file.path(DATA_DIR, "Test_Set_App.xlsx"), sample_sheet = "CALCIUM"
  ),
  IRON = list(
    label = "Iron", symbol = "Fe", unit = "mg/L", task = "classification",
    color = "#BC6C25",
    scope_range = "Binary classification relative to the 10 mg/L limit",
    n_samples = "160 (69 white, 91 red; includes spiked samples)",
    model_desc = "SVM (radial kernel), no additional preprocessing, Boruta selection (58 variables).",
    spiked = TRUE, limit = 10,
    model_file = file.path(MODELS_DIR, "IRON_model.rds"),
    sample_file = file.path(DATA_DIR, "Test_Set_App.xlsx"), sample_sheet = "IRON"
  ),
  COPPER = list(
    label = "Copper", symbol = "Cu", unit = "mg/L", task = "classification",
    color = "#606C38",
    scope_range = "Binary classification relative to the 1 mg/L limit",
    n_samples = "159 (70 white, 89 red; includes spiked samples)",
    model_desc = "SVM (radial kernel), SNV correction, Boruta selection (77 variables).",
    spiked = TRUE, limit = 1,
    model_file = file.path(MODELS_DIR, "COPPER_model.rds"),
    sample_file = file.path(DATA_DIR, "Test_Set_App.xlsx"), sample_sheet = "COPPER"
  )
)

# --------------------------------------------------------------------
# Lazy, cached loading of each .rds bundle. Returns NULL (without
# crashing the app) if the file has not been generated yet.
# --------------------------------------------------------------------
.bundle_cache <- new.env(parent = emptyenv())
load_bundle <- function(analyte_key) {
  if (!is.null(.bundle_cache[[analyte_key]])) return(.bundle_cache[[analyte_key]])
  path <- ANALYTES[[analyte_key]]$model_file
  if (!file.exists(path)) return(NULL)
  b <- readRDS(path)
  .bundle_cache[[analyte_key]] <- b
  b
}

# --------------------------------------------------------------------
# Downloadable report (self-contained HTML) with the model's detail:
# scope, method, preprocessing, hyperparameters and metrics.
# --------------------------------------------------------------------
render_model_report_html <- function(cfg, bundle) {
  metric_rows <- if (cfg$task == "regression") {
    m <- bundle$metrics
    sprintf(
      "<tr><td>R\u00b2 (test)</td><td>%.3f</td></tr><tr><td>RMSE (test)</td><td>%.2f %s</td></tr>
       <tr><td>RPD (test)</td><td>%.2f</td></tr><tr><td>R\u00b2 (training)</td><td>%.3f</td></tr>
       <tr><td>RMSE (training)</td><td>%.2f %s</td></tr>",
      m$R2_Test, m$RMSE_Test, cfg$unit, m$RPD_Test, m$R2_Train, m$RMSE_Train, cfg$unit)
  } else {
    m <- bundle$metrics
    sprintf(
      "<tr><td>AUC (test)</td><td>%s</td></tr><tr><td>Accuracy (test)</td><td>%.3f</td></tr>
       <tr><td>Kappa (test)</td><td>%.3f</td></tr><tr><td>Sensitivity (test)</td><td>%.3f</td></tr>
       <tr><td>Specificity (test)</td><td>%.3f</td></tr>",
      ifelse(is.na(m$AUC_Test), "N/A", sprintf("%.3f", m$AUC_Test)),
      m$Accuracy_Test, m$Kappa_Test, m$Sensitivity_Test, m$Specificity_Test)
  }
  hp <- paste(sprintf("%s = %s", names(bundle$hyperparams), unlist(bundle$hyperparams)), collapse = "; ")
  sprintf('<html><head><meta charset="utf-8"><style>
    body{font-family:Arial,Helvetica,sans-serif;max-width:800px;margin:2em auto;color:#222}
    h1{color:%s} table{border-collapse:collapse;width:100%%;margin:1em 0}
    td,th{border:1px solid #ccc;padding:6px 10px;text-align:left} th{background:#f2f2f2}
    .disclaimer{background:#fff3cd;border:1px solid #ffe08a;padding:1em;border-radius:6px;margin-top:2em}
  </style></head><body>
  <h1>WineMetalScan &mdash; Model sheet: %s (%s)</h1>
  <p><i>Generated: %s</i></p>
  <h2>Scope</h2>
  <table><tr><th>Validated range</th><td>%s</td></tr>
  <tr><th>No. of samples (total)</th><td>%s</td></tr>
  <tr><th>No. training / test</th><td>%d / %d</td></tr>
  <tr><th>Varieties and origin</th><td>%s</td></tr></table>
  <h2>Instrument and reference method</h2>
  <table><tr><th>FT-MIR</th><td>%s</td></tr>
  <tr><th>Reference method</th><td>%s</td></tr></table>
  <h2>Sample preparation (Na<sub>2</sub>EDTA)</h2>
  <p>%s</p>
  <h2>Model</h2>
  <table><tr><th>Algorithm and preprocessing</th><td>%s</td></tr>
  <tr><th>Hyperparameters</th><td>%s</td></tr></table>
  <h2>Performance metrics</h2>
  <table><tr><th>Metric</th><th>Value</th></tr>%s</table>
  <div class="disclaimer"><b>Disclaimer:</b> %s</div>
  </body></html>',
  cfg$color, cfg$label, cfg$symbol, format(Sys.time(), "%Y-%m-%d %H:%M"),
  cfg$scope_range, cfg$n_samples, bundle$n_train, bundle$n_test, COMMON_INFO$wine_scope,
  COMMON_INFO$instrument, COMMON_INFO$reference_method, COMMON_INFO$edta_protocol,
  cfg$model_desc, hp, metric_rows, COMMON_INFO$disclaimer)
}

render_prediction_report_html <- function(cfg, result) {
  body <- if (result$task == "regression") {
    sprintf("<p style='font-size:1.4em'><b>%.1f %s</b> (approx. 95%% interval: %.1f - %.1f %s)</p>
             <p>Estimated uncertainty: &plusmn; 2 &times; test RMSE (%.1f %s).</p>",
            result$value, cfg$unit, result$lower, result$upper, cfg$unit, result$uncertainty / 2, cfg$unit)
  } else {
    probs <- paste(sprintf("%s: %.1f%%", vapply(names(result$probabilities), pretty_class, "", cfg = cfg),
                           as.numeric(result$probabilities) * 100), collapse = "<br>")
    sprintf("<p style='font-size:1.4em'><b>%s</b></p><p>Class probabilities:<br>%s</p>",
            pretty_class(result$class, cfg), probs)
  }
  resample_note <- if (isTRUE(result$resampled)) {
    "<p><i>Note: the uploaded spectrum did not match the model's reference grid; it was resampled by linear interpolation before prediction.</i></p>"
  } else ""
  sprintf('<html><head><meta charset="utf-8"><style>
    body{font-family:Arial,Helvetica,sans-serif;max-width:700px;margin:2em auto;color:#222}
    h1{color:%s} .disclaimer{background:#fff3cd;border:1px solid #ffe08a;padding:1em;border-radius:6px;margin-top:2em}
  </style></head><body>
  <h1>WineMetalScan &mdash; Prediction result: %s (%s)</h1>
  <p><i>Generated: %s</i><br>Sample: <b>%s</b></p>
  %s %s
  <div class="disclaimer"><b>Disclaimer:</b> %s</div>
  </body></html>',
  cfg$color, cfg$label, cfg$symbol, format(Sys.time(), "%Y-%m-%d %H:%M"),
  if (is.null(result$sample_id)) "-" else result$sample_id, body, resample_note,
  COMMON_INFO$disclaimer)
}


# Readable class names: the models store sanitised names such as
# "Lower.than.10.mg.L"; show them as "Lower than 10 mg/L".
pretty_class <- function(cl, cfg) {
  if (is.null(cfg$limit)) return(gsub("\\.", " ", cl))
  sprintf("%s than %g %s", sub("^([A-Za-z]+).*", "\\1", cl), cfg$limit, cfg$unit)
}

# Row-binds data frames that may have different columns (e.g. a sample
# that failed has no prediction columns), filling the gaps with NA.
dplyr_free_rbind <- function(dfs) {
  cols <- unique(unlist(lapply(dfs, names)))
  dfs <- lapply(dfs, function(d) { for (cn in setdiff(cols, names(d))) d[[cn]] <- NA; d[, cols, drop = FALSE] })
  do.call(rbind, dfs)
}

# ==========================================================================
# Shiny module: one full tab per analyte
# ==========================================================================
analyteUI <- function(id, cfg) {
  ns <- NS(id)
  tagList(
    layout_columns(
      col_widths = c(4, 8),
      # ---------------- Left column: scope and downloads ----------------
      card(
        card_header(style = sprintf("background:%s;color:white;font-weight:600;", cfg$color),
                     sprintf("%s (%s) \u2014 Scope and traceability", cfg$label, cfg$symbol)),
        card_body(
          tags$table(class = "table table-sm",
            tags$tr(tags$td(tags$b("Validated range")), tags$td(cfg$scope_range)),
            tags$tr(tags$td(tags$b("Samples")), tags$td(cfg$n_samples)),
            tags$tr(tags$td(tags$b("Winning model")), tags$td(cfg$model_desc))
          ),
          if (isTRUE(cfg$spiked))
            div(class = "alert alert-secondary", style = "font-size:0.9em",
                "Part of the validation range was obtained by spiking commercial wines with the analyte of interest, ",
                "to cover concentrations rarely found in the natural matrix. See the model sheet for details."),
          tags$hr(),
          tags$b("Grape varieties and origin"), tags$p(COMMON_INFO$wine_scope, style = "font-size:0.9em"),
          tags$b("FT-MIR instrument"), tags$p(COMMON_INFO$instrument, style = "font-size:0.9em"),
          tags$b("Reference method (true values)"), tags$p(COMMON_INFO$reference_method, style = "font-size:0.9em"),
          tags$hr(),
          accordion(
            open = FALSE,
            accordion_panel("Sample preparation protocol (Na\u2082EDTA)",
                             p(COMMON_INFO$edta_protocol))
          ),
          tags$hr(),
          downloadButton(ns("dl_sample"), "Download validation dataset", class = "btn-primary btn-sm w-100 mb-2"),
          downloadButton(ns("dl_model_html"), "Download model summary sheet", class = "btn-primary btn-sm w-100"),
          tags$hr(),
          div(class = "alert alert-warning", style = "font-size:0.85em", COMMON_INFO$disclaimer)
        )
      ),
      # ---------------- Right column: validation + prediction ----------------
      div(
        card(
          card_header("Model validation status"),
          card_body(
            actionButton(ns("btn_validate"), "View validation status", class = "btn-primary mb-3"),
            uiOutput(ns("validation_ui"))
          )
        ),
        card(
          card_header("Predict from your own spectrum"),
          card_body(
            p("Upload an FT-MIR spectrum covering 900\u20133000 cm\u207b\u00b9 as a .csv or .xlsx file, ",
              "using one of the two layouts below. Do NOT include the concentration or class: ",
              "it is not needed (and never used) for prediction.",
              style = "font-size:0.9em; color:#555"),
            accordion(
              open = FALSE,
              accordion_panel(
                "How to format your file (click to see examples)",
                tags$b("Option A \u2014 one spectrum, two columns"),
                tags$table(class = "table table-sm table-bordered w-auto mt-1",
                  tags$thead(tags$tr(tags$th("Wavenumber (cm\u207b\u00b9)"), tags$th("Absorbance"))),
                  tags$tbody(
                    tags$tr(tags$td("902.57"), tags$td("0.0123")),
                    tags$tr(tags$td("906.42"), tags$td("0.0145")),
                    tags$tr(tags$td("910.28"), tags$td("0.0161")),
                    tags$tr(tags$td("\u2026"), tags$td("\u2026")))),
                tags$b("Option B \u2014 several samples, one row per sample"),
                tags$table(class = "table table-sm table-bordered mt-1", style = "font-size:0.85em",
                  tags$thead(tags$tr(tags$th("Sample name"), tags$th("902.57"), tags$th("906.42"),
                                      tags$th("910.28"), tags$th("\u2026"), tags$th("3000.84"))),
                  tags$tbody(
                    tags$tr(tags$td("Wine_1"), tags$td("0.0123"), tags$td("0.0145"), tags$td("0.0161"), tags$td("\u2026"), tags$td("0.0072")),
                    tags$tr(tags$td("Wine_2"), tags$td("0.0119"), tags$td("0.0140"), tags$td("0.0158"), tags$td("\u2026"), tags$td("0.0069")))),
                tags$ul(style = "font-size:0.85em",
                  tags$li("First row = headers. In Option B the headers of the spectral columns must be the wavenumbers (numbers)."),
                  tags$li("The first column is used only as the sample name. Any other non-spectral column (e.g. 'Group') is ignored."),
                  tags$li("If your instrument uses a different step or range, the spectrum is automatically realigned (it must still cover ~900\u20133000 cm\u207b\u00b9)."),
                  tags$li("Practice files with known values are in the 'Download validation dataset' button on the left; the true value is written in each sample name (REF=...)."))
              )
            ),
            fileInput(ns("spectrum_file"), NULL, accept = c(".csv", ".xlsx")),
            uiOutput(ns("sample_picker_ui")),
            actionButton(ns("btn_predict"), "Predict", class = "btn-primary mb-3"),
            uiOutput(ns("prediction_ui"))
          )
        )
      )
    )
  )
}

analyteServer <- function(id, cfg) {
  moduleServer(id, function(input, output, session) {

    bundle <- reactive(load_bundle(id))

    # ---------------- Downloads ----------------
    output$dl_sample <- downloadHandler(
      filename = function() sprintf("Validation_samples_%s.xlsx", cfg$symbol),
      content = function(file) {
        # export ONLY this analyte's sheet (not the whole multi-sheet workbook)
        df <- openxlsx::read.xlsx(cfg$sample_file, sheet = cfg$sample_sheet, check.names = FALSE)
        wb <- openxlsx::createWorkbook()
        openxlsx::addWorksheet(wb, cfg$sample_sheet)
        openxlsx::writeData(wb, cfg$sample_sheet, df)
        openxlsx::saveWorkbook(wb, file, overwrite = TRUE)
      }
    )
    output$dl_model_html <- downloadHandler(
      filename = function() sprintf("Model_sheet_%s.html", cfg$symbol),
      content = function(file) {
        b <- bundle()
        validate(need(!is.null(b), "The model is not available yet."))
        writeLines(render_model_report_html(cfg, b), file)
      }
    )

    # ---------------- Validation status ----------------
    output$validation_ui <- renderUI({
      req(input$btn_validate > 0)
      b <- bundle()
      ns <- session$ns
      if (is.null(b)) {
        return(div(class = "alert alert-danger",
                    "The model for this analyte is not loaded on the server yet."))
      }
      if (cfg$task == "regression") {
        tagList(
          h5("Winning model hyperparameters"),
          p(paste(sprintf("%s = %s", names(b$hyperparams), unlist(b$hyperparams)), collapse = "; ")),
          DTOutput(ns("metrics_table")),
          plotOutput(ns("scatter_plot"), height = "380px")
        )
      } else {
        tagList(
          h5("Winning model hyperparameters"),
          p(paste(sprintf("%s = %s", names(b$hyperparams), unlist(b$hyperparams)), collapse = "; ")),
          DTOutput(ns("metrics_table")),
          plotOutput(ns("confusion_plot"), height = "320px"),
          tags$hr(),
          h5("Hierarchical clustering of the samples (unsupervised)"),
          p("Compares whether the groups formed by the spectrum alone (branch colour) match the actual class (label colour).",
            style = "font-size:0.85em;color:#666"),
          plotOutput(ns("dendrogram_plot"), height = "480px")
        )
      }
    })

    output$metrics_table <- renderDT({
      req(input$btn_validate > 0)
      b <- bundle(); validate(need(!is.null(b), "Model not available."))
      m <- b$metrics
      df <- if (cfg$task == "regression") {
        data.frame(Metric = c("R\u00b2", "RMSE", "RPD"),
                   Training = c(round(m$R2_Train, 3), round(m$RMSE_Train, 2), round(m$RPD_Train, 2)),
                   Test = c(round(m$R2_Test, 3), round(m$RMSE_Test, 2), round(m$RPD_Test, 2)))
      } else {
        data.frame(Metric = c("AUC", "Accuracy", "Kappa", "Sensitivity", "Specificity"),
                   Test = c(round(m$AUC_Test, 3), round(m$Accuracy_Test, 3), round(m$Kappa_Test, 3),
                            round(m$Sensitivity_Test, 3), round(m$Specificity_Test, 3)))
      }
      datatable(df, options = list(dom = "t", paging = FALSE), rownames = FALSE)
    })

    output$scatter_plot <- renderPlot({
      req(input$btn_validate > 0, cfg$task == "regression")
      b <- bundle(); validate(need(!is.null(b), "Model not available."))
      ggplot(b$scatter_data, aes(x = Actual, y = Predicted, color = Set)) +
        geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "grey40") +
        geom_point(size = 2.5, alpha = 0.8) +
        scale_color_manual(values = c(Train = "#457B9D", Test = "#E07B00")) +
        labs(x = sprintf("Measured %s (%s)", cfg$label, cfg$unit),
             y = sprintf("Predicted %s (%s)", cfg$label, cfg$unit), color = NULL) +
        theme_minimal(base_size = 13)
    })

    output$confusion_plot <- renderPlot({
      req(input$btn_validate > 0, cfg$task == "classification")
      b <- bundle(); validate(need(!is.null(b), "Model not available."))
      te <- b$scatter_data
      te$Actual    <- pretty_class(as.character(te$Actual), cfg)
      te$Predicted <- pretty_class(as.character(te$Predicted), cfg)
      cm <- as.data.frame(table(Actual = te$Actual, Predicted = te$Predicted))
      ggplot(cm, aes(x = Actual, y = Predicted, fill = Freq)) +
        geom_tile(color = "white") +
        geom_text(aes(label = Freq), size = 6, fontface = "bold") +
        scale_fill_gradient(low = "#f2f2f2", high = cfg$color) +
        labs(title = "Confusion matrix (test)") +
        theme_minimal(base_size = 12) + theme(axis.text.x = element_text(angle = 20, hjust = 1))
    })

    output$dendrogram_plot <- renderPlot({
      req(input$btn_validate > 0, cfg$task == "classification")
      b <- bundle(); validate(need(!is.null(b), "Model not available."))
      validate(need(!is.null(b$dendro_hc), "Dendrogram not available for this model."))
      render_dendrogram(b, cfg$color, cfg$limit, cfg$unit)
    })

    # ---------------- Prediction on a new spectrum ----------------
    # The uploaded file is parsed as soon as it arrives; problems are shown
    # as a visible message (Shiny hides raw R errors on the server).
    parsed <- reactive({
      req(input$spectrum_file)
      tryCatch(
        read_uploaded_spectra(input$spectrum_file$datapath, sheet_hint = id),
        error = function(e) list(error = conditionMessage(e)))
    })

    output$sample_picker_ui <- renderUI({
      p <- parsed()
      if (!is.null(p$error)) {
        return(div(class = "alert alert-danger", style = "font-size:0.85em",
                    "Could not read the file: ", p$error))
      }
      if (length(p$ids) > 1) {
        selectInput(session$ns("sample_pick"),
                    sprintf("The file contains %d samples. Predict:", length(p$ids)),
                    choices = c(setNames("all", "All samples"),
                                setNames(seq_along(p$ids), p$ids)),
                    selected = "all")
      } else {
        div(class = "text-muted", style = "font-size:0.85em", "1 spectrum detected.")
      }
    })

    pred_result <- eventReactive(input$btn_predict, {
      b <- bundle()
      if (is.null(b)) return(list(error = "The model for this analyte is not available yet."))
      if (is.null(input$spectrum_file)) return(list(error = "Upload a spectrum first."))
      p <- parsed()
      if (!is.null(p$error)) return(list(error = paste("Could not read the file:", p$error)))

      pick <- if (length(p$ids) > 1 && !is.null(input$sample_pick)) input$sample_pick else "1"

      # ---- all samples together: one row per sample in a table ----
      if (identical(pick, "all")) {
        rows <- lapply(seq_len(nrow(p$ab)), function(i) {
          tryCatch({
            r <- predict_spectrum(b, p$wn, p$ab[i, ])
            if (r$task == "regression") {
              data.frame(Sample = p$ids[i], Predicted = round(r$value, 2),
                         Lower_95 = round(r$lower, 2), Upper_95 = round(r$upper, 2),
                         Note = if (isTRUE(r$resampled)) "Resampled to model grid" else "",
                         check.names = FALSE, stringsAsFactors = FALSE)
            } else {
              pr <- r$probabilities
              out <- data.frame(Sample = p$ids[i], Predicted_class = pretty_class(r$class, cfg),
                                check.names = FALSE, stringsAsFactors = FALSE)
              for (cl in names(pr)) out[[paste0("P(", pretty_class(cl, cfg), ")")]] <- round(as.numeric(pr[[cl]]), 3)
              out$Note <- if (isTRUE(r$resampled)) "Resampled to model grid" else ""
              out
            }
          }, error = function(e) {
            data.frame(Sample = p$ids[i], Note = paste("Failed:", conditionMessage(e)),
                       check.names = FALSE, stringsAsFactors = FALSE)
          })
        })
        tab <- dplyr_free_rbind(rows)
        return(list(task = b$task, multi = TRUE, table = tab))
      }

      # ---- a single sample ----
      i <- suppressWarnings(as.integer(pick))
      if (is.na(i) || i < 1 || i > nrow(p$ab)) i <- 1L
      tryCatch({
        res <- predict_spectrum(b, p$wn, p$ab[i, ])
        res$sample_id <- p$ids[i]
        res
      }, error = function(e) list(error = paste("Prediction failed:", conditionMessage(e))))
    })

    output$prediction_ui <- renderUI({
      res <- pred_result()
      ns <- session$ns
      if (!is.null(res$error)) {
        return(div(class = "alert alert-danger", res$error))
      }
      if (isTRUE(res$multi)) {
        return(tagList(
          div(class = "text-muted", style = "font-size:0.85em;margin-bottom:6px;",
              if (res$task == "regression")
                sprintf("Values in %s. Interval = prediction \u00b1 2\u00d7 test RMSE (approx. 95%%).", cfg$unit)
              else "P(class) = probability assigned to each class."),
          DTOutput(ns("multi_table")),
          downloadButton(ns("dl_multi"), "Download all results (CSV)", class = "btn-primary btn-sm mt-2")
        ))
      }
      sample_line <- div(style = "font-size:0.85em;color:#666;margin-bottom:6px;",
                         "Sample: ", tags$b(res$sample_id))
      note <- if (isTRUE(res$resampled))
        div(class = "alert alert-info", style = "font-size:0.85em",
            "The uploaded spectrum did not exactly match the model's wavenumber grid; ",
            "it was realigned by interpolation before predicting.")
      else NULL

      if (res$task == "regression") {
        tagList(
          sample_line, note,
          div(class = "p-3 mb-2", style = sprintf("background:%s10;border-left:4px solid %s;", cfg$color, cfg$color),
              h3(sprintf("%.1f %s", res$value, cfg$unit), style = sprintf("color:%s", cfg$color)),
              p(sprintf("Approximate interval (95%%): %.1f \u2013 %.1f %s", res$lower, res$upper, cfg$unit)),
              p(sprintf("Uncertainty: \u00b1 2\u00d7 test RMSE (\u00b1 %.1f %s)", res$uncertainty / 2, cfg$unit),
                style = "font-size:0.85em;color:#666")
          ),
          downloadButton(ns("dl_prediction"), "Download result (report)", class = "btn-primary btn-sm")
        )
      } else {
        probs <- res$probabilities
        tagList(
          sample_line, note,
          div(class = "p-3 mb-2", style = sprintf("background:%s10;border-left:4px solid %s;", cfg$color, cfg$color),
              h3(pretty_class(res$class, cfg), style = sprintf("color:%s", cfg$color)),
              lapply(names(probs), function(cl) {
                pct <- round(as.numeric(probs[[cl]]) * 100, 1)
                div(style = "margin-bottom:6px;",
                    span(sprintf("%s: %.1f%%", pretty_class(cl, cfg), pct)),
                    div(style = sprintf("background:#eee;border-radius:4px;height:10px;width:100%%;"),
                        div(style = sprintf("background:%s;border-radius:4px;height:10px;width:%s%%;", cfg$color, pct))))
              })
          ),
          downloadButton(ns("dl_prediction"), "Download result (report)", class = "btn-primary btn-sm")
        )
      }
    })

    output$multi_table <- renderDT({
      res <- pred_result()
      req(isTRUE(res$multi))
      datatable(res$table, rownames = FALSE,
                options = list(pageLength = 10, scrollX = TRUE, dom = "tip"))
    })

    output$dl_multi <- downloadHandler(
      filename = function() sprintf("Predictions_%s_%s.csv", cfg$symbol, format(Sys.time(), "%Y%m%d_%H%M")),
      content = function(file) {
        res <- pred_result()
        write.csv(res$table, file, row.names = FALSE, na = "")
      }
    )

    output$dl_prediction <- downloadHandler(
      filename = function() sprintf("Prediction_%s_%s.html", cfg$symbol, format(Sys.time(), "%Y%m%d_%H%M")),
      content = function(file) writeLines(render_prediction_report_html(cfg, pred_result()), file)
    )
  })
}

# ==========================================================================
# Visual theme
# ==========================================================================
app_theme <- bs_add_rules(
  bs_theme(
    version = 5, bootswatch = "flatly",
    primary = "#7B1E3A", base_font = font_google("Inter"),
    heading_font = font_google("Source Serif Pro")
  ),
  # Every clickable control uses the same burgundy so users can recognise
  # buttons at a glance: accordion headers ("How to format...", protocol)
  # and the file-upload "Browse" button, in addition to the primary buttons.
  ".accordion-button, .accordion-button:not(.collapsed) {
     background-color: #7B1E3A; color: #ffffff; font-weight: 600; }
   .accordion-button:hover { background-color: #96294A; color: #ffffff; }
   .accordion-button:focus { box-shadow: 0 0 0 0.2rem rgba(123,30,58,.25); }
   .accordion-button::after { filter: brightness(0) invert(1); }
   .btn-default, .btn-file { background-color: #7B1E3A; border-color: #7B1E3A; color: #ffffff; }
   .btn-default:hover, .btn-file:hover { background-color: #96294A; border-color: #96294A; color: #ffffff; }"
)

# ==========================================================================
# Home page
# ==========================================================================
home_panel <- div(
  class = "p-4",
  div(style = "display:flex;align-items:center;gap:24px;margin-bottom:1.5em;flex-wrap:wrap;",
      if (file.exists("www/ivagro_logo.png")) tags$img(src = "ivagro_logo.png", height = "80px"),
      if (file.exists("www/uca_logo.png")) tags$img(src = "uca_logo.png", height = "50px"),
      div(
        h2("WineMetalScan", style = "margin-bottom:0;color:#7B1E3A;"),
        h5("Metal concentration estimation in wine by FT-MIR spectroscopy and machine learning",
           style = "font-weight:400;color:#555;")
      )
  ),
  p("This tool provides access to the machine learning models developed to estimate the ",
    "concentration of potassium, magnesium and calcium, and to classify iron and copper relative ",
    "to their enologically relevant limits (10 and 1 mg/L, respectively), from an FT-MIR spectrum ",
    "of a wine sample prepared with Na2EDTA. Each tab corresponds to one analyte, with its own ",
    "validated model, its scope, and a panel to upload your own spectrum."),
  div(class = "alert alert-warning", COMMON_INFO$disclaimer),
  p(tags$b("Developed at the "),
    tags$a(href = IVAGRO_URL, target = "_blank",
           "Institute of Vine and Wine Research (IVAGRO), University of Cadiz"), "."),
  p(class = "text-muted", style = "font-size:0.85em",
    "App source code: ",
    tags$a(href = APP_CODE_URL, target = "_blank", gsub("https://github.com/", "", APP_CODE_URL))),
  p(class = "text-muted", style = "font-size:0.85em",
    "Study pipelines, raw spectra and reference data: ",
    tags$a(href = STUDY_CODE_URL, target = "_blank", gsub("https://github.com/", "", STUDY_CODE_URL)))
)

# ==========================================================================
# Main UI
# ==========================================================================
ui <- page_navbar(
  title = "WineMetalScan",
  theme = app_theme,
  fillable = FALSE,
  nav_panel("Home", home_panel),
  nav_panel("Potassium (K)", analyteUI("POTASSIUM", ANALYTES$POTASSIUM)),
  nav_panel("Magnesium (Mg)", analyteUI("MAGNESIUM", ANALYTES$MAGNESIUM)),
  nav_panel("Calcium (Ca)", analyteUI("CALCIUM", ANALYTES$CALCIUM)),
  nav_panel("Iron (Fe)", analyteUI("IRON", ANALYTES$IRON)),
  nav_panel("Copper (Cu)", analyteUI("COPPER", ANALYTES$COPPER)),
  nav_spacer(),
  nav_item(tags$a(href = IVAGRO_URL, target = "_blank", "IVAGRO \u2014 University of Cadiz"))
)

# ==========================================================================
# Main server
# ==========================================================================
server <- function(input, output, session) {
  # NOTE: lapply() is used on purpose instead of a plain for() loop. With
  # a for(), the loop variable is shared across iterations and, because
  # Shiny evaluates these functions lazily, all 5 modules would end up
  # referencing the LAST analyte of the loop (a well-known Shiny pitfall
  # when instantiating modules inside a for loop).
  lapply(names(ANALYTES), function(k) analyteServer(k, ANALYTES[[k]]))
}

shinyApp(ui, server)
